using System.Text;

namespace MavCs.Tools;

class Program
{
    static void Main(string[] args)
    {
        var currentDir = Directory.GetCurrentDirectory();
        string corePath;

        if (Directory.Exists(Path.Combine(currentDir, "MavCs.Core")))
            corePath = Path.Combine(currentDir, "MavCs.Core");
        else if (Directory.Exists(Path.Combine(currentDir, "..", "MavCs.Core")))
            corePath = Path.Combine(currentDir, "..", "MavCs.Core");
        else
        {
            Console.WriteLine("❌ Error: Could not locate 'MavCs.Core' directory.");
            return;
        }

        var outputPath = Path.Combine(corePath, "Registry", "KnownMessages.cs");
        var outputDir = Path.GetDirectoryName(outputPath);
        if (!Directory.Exists(outputDir)) Directory.CreateDirectory(outputDir!);

        Console.WriteLine("🚀 MavCs Registry Generator");
        Console.WriteLine($"Target: {Path.GetFullPath(outputPath)}");

        var sb = new StringBuilder();

        
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by MavCs.Tools. Do not modify manually.");
        sb.AppendLine($"// Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Frozen;"); 
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using MavCs.Core.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace MavCs.Core.Registry;");
        sb.AppendLine();
        
        sb.AppendLine("public sealed class KnownMessages : IMessageRegistry");
        sb.AppendLine("{");
        
        sb.AppendLine("    // MsgId -> CrcExtra mapping (Static & Fast)");
        sb.AppendLine("    private static readonly FrozenDictionary<uint, byte> CrcMap = new Dictionary<uint, byte>");
        sb.AppendLine("    {");

        var messages = new Dictionary<uint, (byte Crc, string Name)>
        {
            { 0,   (50,  "HEARTBEAT") },
            { 1,   (124, "SYS_STATUS") },
            { 20,  (214, "PARAM_REQUEST_READ") },
            { 22,  (220, "PARAM_VALUE") },
            { 23,  (168, "PARAM_SET") },
            { 24,  (24,  "GPS_RAW_INT") },
            { 30,  (39, "ATTITUDE") },
            { 33,  (104, "GLOBAL_POSITION_INT") },
            { 36,  (222, "SERVO_OUTPUT_RAW") },
            { 40,  (230, "MISSION_REQUEST") },
            { 44,  (221, "MISSION_COUNT") },
            { 47,  (153, "MISSION_ACK") },
            { 65,  (118, "RC_CHANNELS") },
            { 73,  (38,  "MISSION_ITEM_INT") },
            { 74,  (20,  "VFR_HUD") },
            { 76,  (152, "COMMAND_LONG") },
            { 147, (154, "BATTERY_STATUS") },
            { 148, (178, "AUTOPILOT_VERSION") },
            { 242, (104, "HOME_POSITION") },
            { 253, (83,  "STATUSTEXT") }
        };

        foreach (var item in messages.OrderBy(x => x.Key))
        {
            sb.AppendLine($"        {{ {item.Key}, {item.Value.Crc} }}, // {item.Value.Name}");
        }

        sb.AppendLine("    }.ToFrozenDictionary();");
        sb.AppendLine();
        
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Retrieves the CRC_EXTRA byte for a given message ID.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public byte? GetCrcExtra(uint messageId)");
        sb.AppendLine("    {");
        sb.AppendLine("        return CrcMap.TryGetValue(messageId, out var crc) ? crc : null;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine("✅ KnownMessages.cs successfully updated (Interface compliance restored).");
    }
}
