// <auto-generated>
// This code was generated by MavCs.Tools. Do not modify manually.
// Generated at: 2026-01-30 15:20:44 UTC
// </auto-generated>

using System.Collections.Frozen;
using System.Collections.Generic;
using MavCs.Core.Abstractions;

namespace MavCs.Core.Registry;

public sealed class KnownMessages : IMessageRegistry
{
    // MsgId -> CrcExtra mapping (Static & Fast)
    private static readonly FrozenDictionary<uint, byte> CrcMap = new Dictionary<uint, byte>
    {
        { 0, 50 }, // HEARTBEAT
        { 1, 124 }, // SYS_STATUS
        { 20, 214 }, // PARAM_REQUEST_READ
        { 22, 220 }, // PARAM_VALUE
        { 23, 168 }, // PARAM_SET
        { 24, 24 }, // GPS_RAW_INT
        { 30, 39 }, // ATTITUDE
        { 33, 104 }, // GLOBAL_POSITION_INT
        { 36, 222 }, // SERVO_OUTPUT_RAW
        { 40, 230 }, // MISSION_REQUEST
        { 44, 221 }, // MISSION_COUNT
        { 47, 153 }, // MISSION_ACK
        { 65, 118 }, // RC_CHANNELS
        { 73, 38 }, // MISSION_ITEM_INT
        { 74, 20 }, // VFR_HUD
        { 76, 152 }, // COMMAND_LONG
        { 147, 154 }, // BATTERY_STATUS
        { 148, 178 }, // AUTOPILOT_VERSION
        { 242, 104 }, // HOME_POSITION
        { 253, 83 }, // STATUSTEXT
    }.ToFrozenDictionary();

    /// <summary>
    /// Retrieves the CRC_EXTRA byte for a given message ID.
    /// </summary>
    public byte? GetCrcExtra(uint messageId)
    {
        return CrcMap.TryGetValue(messageId, out var crc) ? crc : null;
    }
}
